[tool.poetry]
name = "poetry-problem"
version = "0.1.0"
description = ""
authors = ["Christian Franke <nobody@nowhere.ws>"]

[tool.poetry.dependencies]
python = "^3.7"
wagtail = "2.7.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
